/* The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 +2 +3 +4 +5 +6 +7 =28. The first ten terms would be:
1,3,6,10,15,21,28,36,45,55,…

Let us list the factors of the first seven triangle numbers:

𝟏	:1
𝟑	:1,3
𝟔	:1,2,3,6
𝟏𝟎	:1,2,5,10
𝟏𝟓	:1,3,5,15
𝟐𝟏	:1,3,7,21
𝟐𝟖	:1,2,4,7,14,28
 
We can see that 28 is the first triangle number to have over five divisors
What is the value of the first triangle number to have over five hundred divisors */
#include <stdio.h>
int countdivisor(long long number)
{
    int divisor = 1;
    int count = 0;
    while (number % 2 == 0)
    {
        number /= 2;
        count++;
    }
    divisor *= (count + 1);
    int i = 3;
    count = 0;
    while (number > 1)
    {
        if (number % i == 0)
        {
            number /= i;
            count++;
        }
        if (number %i !=0)
        {
            divisor *= (count + 1);
            count = 0;
            i += 2;
        }
    }
    return divisor;
}
int main()
{
    int i=1;
    while (1)
    {
        int number = i * (i + 1) / 2;
        if (countdivisor(number) > 500)
        {
            printf("%d",number);
            break;
        }
        i++;
    }

    return 0;
}