# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 +2 +3 +4 +5 +6 +7 =28. The first ten terms would be:
# 1,3,6,10,15,21,28,36,45,55,…

# Let us list the factors of the first seven triangle numbers:

# 𝟏	:1
# 𝟑	:1,3
# 𝟔	:1,2,3,6
# 𝟏𝟎	:1,2,5,10
# 𝟏𝟓	:1,3,5,15
# 𝟐𝟏	:1,3,7,21
# 𝟐𝟖	:1,2,4,7,14,28
 
# We can see that 28 is the first triangle number to have over five divisors
# What is the value of the first triangle number to have over five hundred divisors

import math

def count_divisors(n):

    divisors = 1
    count = 0
    
    while n % 2 == 0:
        count += 1
        n //= 2
    divisors *= (count + 1)
    
    p = 3
    while p * p <= n:
        count = 0
        while n % p == 0:
            count += 1
            n //= p
        divisors *= (count + 1)
        p += 2
        
    if n > 1:
        divisors *= 2
        
    return divisors

n = 1
while True:
    triangle_number = (n * (n + 1)) // 2
    
    if count_divisors(triangle_number) > 500:
        print(f"Sıra: {n}")
        print(f"Üçgensel Sayı: {triangle_number}")
        break
        
    n += 1